python sdpra_script.py \
    --seed 144 \
    --shots 5 \
    --calibration True \
    --max_seq_length 256 \
    --batch_size 5 \
    --max_epochs 5 \
    --cuda_device 0 \
    --learning_rate 3e-5 \
    --soft_verbalizer False \ # whether using the Soft verbalization method
    --data_dir "/path/to/your/data/" \ # e.g., data/SDPRA
    --verbalizer_path "knowledge_output/SDPRA_output_words.txt" \ # filtered verbalizer
    --semantic_score_path "scores/SDPRA_output_scores.tx" \
    --doc_id_path "data/SDPRA/label_dict.txt" \
    --config_path "label_mappings/SDPRA_label_mappings.json" \
    --zero_shot no
